postgres_user: admin
postgres_db: ysp-app-db
postgres_port: 5432

backend_port: 8080
frontend_port: 3000
nginx_http_port: 80
nginx_https_port: 443

cors_origin: "http://147.93.191.183"
from_email: "noreply@ysp.local"
mailpit_smtp_port: 1025
mailpit_web_port: 8025
jwt_ttl: 3600
app_logo_url: ""
app_public_base_url: "http://147.93.191.183"

admin_email: "ntalegeofrey@gmail.com"
admin_password: "Amandagowa@393"